{{- range .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "krusty.fullname" $ }}-{{ .name }}
  labels:
    {{- include "krusty.labels" $ | nindent 4 }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}

