{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krusty.fullname" $ }}-{{ .name }}-env
  labels:
    {{- include "krusty.labels" $ | nindent 4 }}
data:
  {{- range $k, $v := .data }}
    {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}