apiVersion: v1
kind: Service
metadata:
  name: {{ include "krusty.fullname" . }}
  labels:
    {{- include "krusty.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "krusty.selectorLabels" . | nindent 4 }}