apiVersion: apps/v1
kind: Deployment
metadata:
  name: krusty
spec:
  selector:
    matchLabels:
      app: krusty
  template:
    metadata:
      labels:
        app: krusty
    spec:
      volumes:
        - name: krusty-config
          configMap:
            name: krusty-config
        - name: redict-data
          persistentVolumeClaim:
            claimName: krusty-redict-data
      imagePullSecrets:
        - name: regcred
      containers:
        - name: redict
          image: registry.redict.io/redict:7-debian
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redict-data
              mountPath: /data
        - name: krusty
          image: ghcr.io/ravenxdoesthings/krusty:v2.0.0-rc2
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          envFrom:
            - secretRef:
                name: krusty-env
          volumeMounts:
            - name: krusty-config
              mountPath: /etc/krusty
